export const FETCH_CONTINENTS = 'FETCH_CONTINENTS';
export const SELECT_CONTINENT = 'SELECT_CONTINENT';
export const SELECT_COUNTRY = 'SELECT_COUNTRY';
export const UN_SELECT_COUNTRY = 'UN_SELECT_COUNTRY';
export const CLEAR_FLAG = 'CLEAR_FLAG';
